# Generated by Django 3.2.6 on 2021-08-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name')),
                ('datebuy', models.DateTimeField(auto_now_add=True)),
                ('datesell', models.DateTimeField()),
                ('price', models.FloatField()),
                ('sellprice', models.FloatField()),
                ('anyprice', models.FloatField()),
                ('value', models.FloatField()),
                ('size', models.CharField(choices=[('5', '5 US'), ('5.5', '5.5 US'), ('6', '6 US'), ('6.5', '6.5 US'), ('7', '7 US'), ('7.5', '7.5 US')], max_length=5, verbose_name='Size')),
                ('notes', models.CharField(max_length=255, verbose_name='Notes')),
            ],
        ),
    ]
