# Generated by Django 3.2.6 on 2021-08-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Sneaker', 'verbose_name_plural': 'Sneakers'},
        ),
        migrations.AlterField(
            model_name='table',
            name='anyprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='datesell',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='table',
            name='sellprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
