# Generated by Django 3.2.6 on 2021-08-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210817_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='value',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
