# Generated by Django 3.2.6 on 2021-08-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_table_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='datebuy',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='datesell',
            field=models.DateField(blank=True, null=True),
        ),
    ]
