# Generated by Django 3.2.6 on 2021-08-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210817_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='datebuy',
            field=models.DateField(null=True),
        ),
    ]
