# Generated by Django 3.2.6 on 2021-08-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_table_datebuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Notes'),
        ),
    ]
