# Generated by Django 3.2.6 on 2021-08-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_table_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='anyprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='table',
            name='sellprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=19, null=True),
        ),
    ]
