# Generated by Django 3.2.6 on 2021-08-22 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210821_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='datebuy',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
