# Generated by Django 3.2.6 on 2021-08-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_table_datebuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='datebuy',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='size',
            field=models.CharField(choices=[('0', 'NO SIZE'), ('3', '3 US'), ('3.5', '3.5 US'), ('4', '4 US'), ('4.5', '4.5 US'), ('5', '5 US'), ('5.5', '5.5 US'), ('6', '6 US'), ('6.5', '6.5 US'), ('7', '7 US'), ('7.5', '7.5 US'), ('8', '8 US'), ('8.5', '8.5 US'), ('9', '9 US'), ('9.5', '9.5 US'), ('10', '10 US'), ('10.5', '10.5 US'), ('11', '11 US'), ('11.5', '11.5 US'), ('12', '12 US'), ('12.5', '12.5 US'), ('13', '13 US'), ('13.5', '13.5 US'), ('14', '14 US'), ('14.5', '14.5 US'), ('15', '15 US')], max_length=5, verbose_name='Size'),
        ),
    ]
