# Generated by Django 3.2.6 on 2021-09-10 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_alter_table_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='anyprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='table',
            name='sellprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name')),
                ('datemeeting', models.DateField(null=True)),
                ('sellprice', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='Notes')),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
            },
        ),
    ]
