# Generated by Django 3.2.6 on 2021-09-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_meetings_iditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
    ]
