# Generated by Django 3.2.6 on 2021-10-17 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_table_meet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='meet',
            field=models.ForeignKey(default=40, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.meetings'),
        ),
    ]
