# Generated by Django 3.2.6 on 2021-09-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_meetings_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetings',
            old_name='item_id',
            new_name='item_ID',
        ),
    ]
