# Generated by Django 3.2.6 on 2021-09-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_item_id_meetings_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetings',
            name='item_ID',
        ),
        migrations.AddField(
            model_name='meetings',
            name='test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
