# Generated by Django 3.2.6 on 2021-10-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20211018_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='sellprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='possibleprice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.potentialsellprice'),
        ),
    ]
