# Generated by Django 3.2.6 on 2021-09-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_meetings_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='test',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
