# Generated by Django 3.2.6 on 2021-10-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_table_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='currency',
        ),
        migrations.AddField(
            model_name='table',
            name='currencybuy',
            field=models.CharField(blank=True, choices=[('rub', '₽'), ('usd', '$'), ('eur', '€'), ('sol', 'SOL'), ('eth', 'ETH')], max_length=10, verbose_name='CurrencyBuy'),
        ),
        migrations.AddField(
            model_name='table',
            name='currencysell',
            field=models.CharField(choices=[('rub', '₽'), ('usd', '$'), ('eur', '€'), ('sol', 'SOL'), ('eth', 'ETH')], default='0', max_length=10, verbose_name='CurrencySell'),
        ),
    ]
