# Generated by Django 3.2.6 on 2021-10-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_meetings_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetings',
            name='test',
        ),
        migrations.AddField(
            model_name='meetings',
            name='item_id',
            field=models.IntegerField(default=0, verbose_name='item_id'),
        ),
    ]
