# Generated by Django 3.2.6 on 2021-10-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20211031_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='currencyprice',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='table',
            name='currencysellprice',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='table',
            name='anyprice',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='table',
            name='currencybuy',
            field=models.CharField(choices=[('₽', '₽'), ('$', '$'), ('€', '€'), ('SOL', 'SOL'), ('ETH', 'ETH')], default='rub', max_length=10, verbose_name='CurrencyBuy'),
        ),
        migrations.AlterField(
            model_name='table',
            name='currencysell',
            field=models.CharField(choices=[('₽', '₽'), ('$', '$'), ('€', '€'), ('SOL', 'SOL'), ('ETH', 'ETH')], default='rub', max_length=10, verbose_name='CurrencySell'),
        ),
        migrations.AlterField(
            model_name='table',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='table',
            name='sellprice',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='table',
            name='size',
            field=models.CharField(choices=[('NO SIZE', 'NO SIZE'), ('3', '3 US'), ('3.5', '3.5 US'), ('4', '4 US'), ('4.5', '4.5 US'), ('5', '5 US'), ('5.5', '5.5 US'), ('6', '6 US'), ('6.5', '6.5 US'), ('7', '7 US'), ('7.5', '7.5 US'), ('8', '8 US'), ('8.5', '8.5 US'), ('9', '9 US'), ('9.5', '9.5 US'), ('10', '10 US'), ('10.5', '10.5 US'), ('11', '11 US'), ('11.5', '11.5 US'), ('12', '12 US'), ('12.5', '12.5 US'), ('13', '13 US'), ('13.5', '13.5 US'), ('14', '14 US'), ('14.5', '14.5 US'), ('15', '15 US')], default='NO SIZE', max_length=10, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='table',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=19, null=True),
        ),
    ]
