# Generated by Django 3.2.6 on 2021-10-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20211031_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='table',
            name='sellprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
