# Generated by Django 3.2.6 on 2021-11-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_table_anyprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
    ]
