# Generated by Django 3.2.6 on 2021-11-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_table_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='datemeeting',
            field=models.DateTimeField(null=True),
        ),
    ]
