# Generated by Django 3.2.6 on 2021-11-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_meetings_datemeeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetings',
            old_name='sellprice',
            new_name='sellpricesum',
        ),
        migrations.AlterField(
            model_name='table',
            name='currencybuy',
            field=models.CharField(choices=[('₽', '₽'), ('$', '$'), ('SOL', 'SOL'), ('ETH', 'ETH')], default='rub', max_length=10, verbose_name='CurrencyBuy'),
        ),
        migrations.AlterField(
            model_name='table',
            name='currencysell',
            field=models.CharField(choices=[('₽', '₽'), ('$', '$'), ('SOL', 'SOL'), ('ETH', 'ETH')], default='rub', max_length=10, verbose_name='CurrencySell'),
        ),
    ]
