# Generated by Django 3.2.6 on 2021-11-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20211108_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes'),
        ),
    ]
